Repository NeuraLegion/har-sdk, pull requests merged in 2023-02, with the labels that each got.

#168 fix(oas): handle optional and unexpected security requirements
  packages/oas/src/converter/parts/headers/HeadersConverter.ts
  packages/oas/tests/DefaultConverter.spec.ts
  packages/oas/tests/fixtures/scheme-security-override.oas.result.json
  packages/oas/tests/fixtures/scheme-security-override.oas.yaml
  packages/oas/tests/fixtures/scheme-security.oas.result.json
  packages/oas/tests/fixtures/scheme-security.oas.yaml
  packages/oas/tests/fixtures/scheme-security.swagger.result.json
  packages/oas/tests/fixtures/scheme-security.swagger.yaml
Labels: Type: bug

#170 build(deps): use npm workspaces instead of lerna
  .github/workflows/auto-build.yml
  lerna.json
  package-lock.json
  package.json
  packages/capture/package-lock.json
  packages/core/package-lock.json
  packages/editor/package-lock.json
  packages/oas/package-lock.json
  packages/openapi-sampler/package-lock.json
  packages/postman/package-lock.json
  packages/types/package-lock.json
  packages/validator/package-lock.json
Labels: Type: maintenance

#177 docs(oas): make the description more clear
  packages/oas/README.md
Labels: Type: documentation

#176 feat(oas): add support the file type defined in Swagger 2.0
  packages/oas/src/converter/parts/SubConverterFactory.ts
  packages/oas/src/converter/parts/postdata/BodyConverter.ts
  packages/oas/src/converter/parts/postdata/Oas2BodyConverter.ts
  packages/oas/src/converter/parts/postdata/Oas3RequestBodyConverter.ts
  packages/oas/src/converter/parts/postdata/PostDataConverter.ts
  packages/oas/src/converter/parts/postdata/index.ts
  packages/oas/tests/DefaultConverter.spec.ts
  packages/oas/tests/fixtures/params-encoding.oas.result.json
  packages/oas/tests/fixtures/params-encoding.oas.yaml
  packages/oas/tests/fixtures/params-form-data.swagger.result.json
  packages/oas/tests/fixtures/params-form-data.swagger.yaml
Labels: Type: enhancement

#178 feat(oas): add full support for API key security schemes
  packages/oas/src/converter/DefaultConverter.ts
  packages/oas/src/converter/Sampler.ts
  packages/oas/src/converter/index.ts
  packages/oas/src/converter/parts/BaseUrlParser.ts
  packages/oas/src/converter/parts/SubConverterFactory.ts
  packages/oas/src/converter/parts/headers/HeadersConverter.ts
  packages/oas/src/converter/parts/headers/Oas2HeadersConveter.ts
  packages/oas/src/converter/parts/headers/Oas3HeadersConverter.ts
  packages/oas/src/converter/parts/index.ts
  packages/oas/src/converter/parts/path/Oas2PathConverter.ts
  packages/oas/src/converter/parts/path/Oas3PathConverter.ts
  packages/oas/src/converter/parts/path/PathConverter.ts
  packages/oas/src/converter/parts/postdata/BodyConverter.ts
  packages/oas/src/converter/parts/postdata/Oas2BodyConverter.ts
  packages/oas/src/converter/parts/postdata/Oas3RequestBodyConverter.ts
  packages/oas/src/converter/parts/query/Oas2QueryStringConverter.ts
  packages/oas/src/converter/parts/query/Oas3QueryStringConverter.ts
  packages/oas/src/converter/parts/query/QueryStringConverter.ts
  packages/oas/src/converter/security/Oas2SecurityRequirementsParser.ts
  packages/oas/src/converter/security/Oas3SecurityRequirementsParser.ts
  packages/oas/src/converter/security/SecurityRequirementsFactory.ts
  packages/oas/src/converter/security/SecurityRequirementsParser.ts
  packages/oas/src/converter/security/index.ts
  packages/oas/src/converter/security/schemas/ApiKeyCookieSecurityScheme.ts
  packages/oas/src/converter/security/schemas/ApiKeyHeaderSecurityScheme.ts
  packages/oas/src/converter/security/schemas/ApiKeyQuerySecurityScheme.ts
  packages/oas/src/converter/security/schemas/BasicSecurityScheme.ts
  packages/oas/src/converter/security/schemas/BearerSecurityScheme.ts
  packages/oas/src/converter/security/schemas/HttpSecurityScheme.ts
  packages/oas/src/converter/security/schemas/SecuritySchema.ts
  packages/oas/src/converter/security/schemas/index.ts
  packages/oas/src/index.ts
  packages/oas/src/types/index.ts
  packages/oas/src/utils/index.ts
  packages/oas/src/utils/operation.ts
  packages/oas/src/utils/params.ts
  packages/oas/tests/fixtures/scheme-security.oas.result.json
  packages/oas/tests/fixtures/scheme-security.oas.yaml
Labels: Type: enhancement

#184 docs(openapi-sampler): provide the clear and concise description
  packages/openapi-sampler/README.md
Labels: Type: documentation

#183 fix(oas): xml model serialization
  package-lock.json
  packages/oas/package.json
  packages/oas/src/converter/DefaultConverter.ts
  packages/oas/src/converter/index.ts
  packages/oas/src/converter/parts/postdata/BodyConverter.ts
  packages/oas/src/converter/parts/postdata/Oas2BodyConverter.ts
  packages/oas/src/converter/parts/postdata/Oas3RequestBodyConverter.ts
  packages/oas/src/converter/serializers/Serializer.ts
  packages/oas/src/converter/serializers/XmlObject.ts
  packages/oas/src/converter/serializers/XmlSerializer.ts
  packages/oas/src/converter/serializers/index.ts
  packages/oas/tests/DefaultConverter.spec.ts
  packages/oas/tests/XmlSerializer.spec.ts
  packages/oas/tests/fixtures/params-body-default.oas.result.json
  packages/oas/tests/fixtures/params-body-default.oas.yaml
  packages/oas/tests/fixtures/params-encoding.oas.result.json
  packages/oas/tests/fixtures/params-encoding.oas.yaml
  packages/oas/tests/fixtures/xml-models.oas.result.json
  packages/oas/tests/fixtures/xml-models.oas.yaml
  packages/oas/tests/fixtures/xml-models.swagger.result.json
  packages/oas/tests/fixtures/xml-models.swagger.yaml
  packages/openapi-sampler/src/samplers/ObjectSampler.ts
Labels: Type: bug

#186 feat(openapi-sampler): add support for extra format options
  packages/openapi-sampler/src/samplers/StringSampler.ts
  packages/openapi-sampler/tests/string.spec.ts
Labels: Type: enhancement

#189 docs(oas): loading the spec hosted remotely
  packages/oas/README.md
Labels: Type: documentation

#191 docs(postman): provide clear and concise description
  packages/postman/README.md
Labels: Type: documentation

#195 refactor: improve wording of converting errors
  packages/openapi-sampler/src/samplers/NumberSampler.ts
  packages/openapi-sampler/src/samplers/StringSampler.ts
  packages/openapi-sampler/src/traverse/DefaultTraverse.ts
  packages/openapi-sampler/tests/number.spec.ts
  packages/openapi-sampler/tests/string.spec.ts
  packages/postman/src/converter/DefaultConverter.ts
Labels: Type: technical debt, Type: refactoring

#193 fix(postman): unexpected URL when using variable as host
  packages/core/src/utils/url.ts
  packages/postman/src/converter/DefaultConverter.ts
  packages/postman/tests/DefaultConverter.spec.ts
  packages/postman/tests/fixtures/misused-variable.postman_collection.json
  packages/postman/tests/fixtures/misused-variable.postman_collection.result.json
  packages/postman/tests/fixtures/salesforce-apis.postman_collection.json
  packages/postman/tests/fixtures/salesforce-apis.postman_collection.result.json
Labels: Type: bug

#197 fix(editor): extracting the request body value from variety of examples
  packages/editor/src/editor/oas/v3/OasV3RequestBodyObjectParser.ts
  packages/editor/tests/fixtures/oas3-examples.json
  packages/editor/tests/fixtures/oas3-examples.result.json
  packages/editor/tests/oas3.spec.ts
Labels: Type: bug

#199 fix(openapi-sampler): sampling the binary data
  packages/oas/tests/fixtures/petstore.oas.result.json
  packages/openapi-sampler/src/samplers/StringSampler.ts
  packages/openapi-sampler/tests/string.spec.ts
Labels: Type: bug

#190 fix(oas): serialize binary and base64 data
  packages/oas/src/converter/parts/postdata/BodyConverter.ts
  packages/oas/src/utils/index.ts
  packages/oas/tests/DefaultConverter.spec.ts
  packages/oas/tests/fixtures/binary-body.oas.result.json
  packages/oas/tests/fixtures/binary-body.oas.yaml
  packages/oas/tests/fixtures/binary-body.swagger.result.json
  packages/oas/tests/fixtures/binary-body.swagger.yaml
  packages/oas/tests/fixtures/params-encoding.oas.result.json
Labels: Type: bug
